import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/custom.scss";
import Navbar from "../components/Navbar";
import ClientRoot from "../components/ClientRoot";
import { CartProvider } from "../components/CartContext";
import { DemoAuthProvider } from "../components/DemoAuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DemoAuthProvider>
          <CartProvider>
            <ClientRoot>
              <Navbar />
              {children}
            </ClientRoot>
          </CartProvider>
        </DemoAuthProvider>
      </body>
    </html>
  );
}
